version: '3.1'
services:
  db:
    image: postgres
    container_name: postgres_db
    restart: always
    volumes:
      - ./database/01-db.sql:/docker-entrypoint-initdb.d/01-db.sql
    environment:
      - POSTGRES_PASSWORD=root
    ports:
      - '5432:5432'
