version: '3.8'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: gerenciamento_clientes
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./database/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
      - ./database/populate-data.sql:/docker-entrypoint-initdb.d/populate-data.sql
    networks:
      - backend_network

  backend:
    build:
      context: ./../backend
    environment:
      POSTGRES_LOCAL_PORT: 5432
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: gerenciamento_clientes
      POSTGRES_PASSWORD: root
      PORT: 5000
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    networks:
      - backend_network

  frontend:
    build:
      context: ./../frontend
    environment:
      NEXT_PUBLIC_API_URL: "http://backend:5000"
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - backend_network

networks:
  backend_network: