version: '3.1'
services:
  db:
    image: postgres
    container_name: postgres_db
    restart: always
    volumes:
      - ./database/01-db.sql:/docker-entrypoint-initdb.d/01-db.sql
    environment:
      - POSTGRES_PASSWORD=root
    ports:
      - '5432:5432'

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    environment:
      - PORT=${PORT}
    ports:
      - '5000:5000'
    depends_on:
      - db
    volumes:
      - ./backend/src:/app/src

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - '3000:3000'
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
