# backend\dockerfile nestjs
FROM node:18-alpine

WORKDIR /app

COPY package.json ./

RUN npm install -g @nestjs/cli


RUN npm install

COPY . .

EXPOSE 5000

# RUN npm run build

CMD ["npm", "run", "start:dev"]
